depend: [MECore, MEInventories]
name: ${project.name}
version: ${project.version}
author: ${author}
main: ${corepackage}.meplayerdata.MEPlayerDataPlugin
description: ${project.description}
api-version: ${mc-api-ver}
