depend: [MEPlayerData, MECore, MEItems]
name: ${project.name}
version: ${project.version}
author: ${author}
main: ${corepackage}.meabilities.MEAbilitiesPlugin
description: ${project.description}
api-version: ${mc-api-ver}
