depend: [MEEntities, MEPlayerData, MEItems]
name: ${project.name}
version: ${project.version}
author: ${author}
main: ${corepackage}.mecombat.MECombatPlugin
description: ${project.description}
api-version: ${mc-api-ver}
