depend: [MECore, MEPlayerData]
name: ${project.name}
version: ${project.version}
author: ${author}
main: ${corepackage}.meitems.MEItemsPlugin
description: ${project.description}
api-version: ${mc-api-ver}
