depend: [MECore, MEInventories]
name: ${project.name}
version: ${project.version}
author: ${author}
main: ${corepackage}.mesocial.MESocialPlugin
description: ${project.description}
api-version: ${mc-api-ver}
