depend: [MEPlayerData, MECore, MEItems]
name: MEAbilities
version: 1.0-SNAPSHOT
author: Buby
main: com.buoobuoo.mesuite.meabilities.MEAbilitiesPlugin
description: Ability Management
api-version: 1.19
