depend: [MECore, MEPlayerData]
name: MEPermissions
version: 1.0-SNAPSHOT
author: Buby
main: com.buoobuoo.mesuite.mepermissions.MEPermissionsPlugin
description: Permissions Management
api-version: 1.19
